// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class FuntionaltestreportsTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void funtionaltestreports()
    {
        driver.Navigate().GoToUrl("http://localhost:5064/");
        driver.Manage().Window.Size = new System.Drawing.Size(814, 824);
        driver.FindElement(By.LinkText("Iniciar Sesión")).Click();
        driver.FindElement(By.Id("Input_UserName")).Click();
        driver.FindElement(By.Id("Input_UserName")).SendKeys("anne");
        driver.FindElement(By.Id("Input_Password")).SendKeys("Anne1.");
        driver.FindElement(By.CssSelector(".register_submit")).Click();
        driver.FindElement(By.Id("SearchString")).Click();
        driver.FindElement(By.Id("SearchString")).SendKeys("Pan");
        driver.FindElement(By.Id("searchButton")).Click();
        driver.FindElement(By.CssSelector("tr:nth-child(2) .election")).Click();
        driver.FindElement(By.CssSelector("img")).Click();
        driver.FindElement(By.Id("Report_Comment")).Click();
        driver.FindElement(By.Id("Report_Comment")).SendKeys("El pantalon esta mas caro");
        driver.FindElement(By.CssSelector(".add_confirm"));
        driver.FindElement(By.LinkText("Ver reportes")).Click();
    }
}