// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PruebaTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void prueba()
    {
        driver.Navigate().GoToUrl("http://localhost:5064/");
        driver.Manage().Window.Size = new System.Drawing.Size(796, 824);
        driver.FindElement(By.Id("SearchString")).Click();
        driver.FindElement(By.Id("SearchString")).SendKeys("a");
        driver.FindElement(By.Id("searchButton")).Click();
        driver.FindElement(By.LinkText("Colgate Pasta Total 12 Clean Mint 75ml")).Click();
        driver.FindElement(By.CssSelector("tr:nth-child(1) img")).Click();
        driver.FindElement(By.Id("Report_Comment")).Click();
        driver.FindElement(By.Id("Report_Comment")).SendKeys("El precio no es correcto");
        driver.FindElement(By.CssSelector(".add_confirm")).Click();
    }
}
