name: Keep Container Alive

on:
  schedule:
    - cron: '*/4 * * * *'  # Cada 4 minutos

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep-Alive Request
        run: curl -X GET https://locompro.live
